# -*- coding: utf-8 -*-
"""NBA_Data_Analysis_Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ieHkvKSqAvy6_-5tlm4BO7ZWnxCdd5u-
"""

import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_excel('/content/NBA Project.xlsx')
print(df.shape)
df.head()

# Keeping the important columns.
columns_to_keep = ['Year', 'Player', 'Pos', 'G', 'MP', 'FGA', '3PA', '3P', 'PTS']
df = df[columns_to_keep].copy()

# types of data
print(df.dtypes)

print(df.isnull().sum())
#how much is null?
df = df.dropna(subset=['3PA'])
#fill the empthy cells with 0
df = df.fillna(0)

print("\nMissing values after cleaning:", df.isnull().sum().sum())

# Cleaning the Data. Players who Played more then 10 games and more then 100 minutes
df = df[(df['G'] >= 10) & (df['MP'] >= 100)]
# make sure the showen data is between 1997-2017
df = df[df['Year'] >= 1997]
df.head()

# Initial Cleaning for 1997-2017 and Trade Duplicates
df_all = df[(df['Year'] >= 1997) & (df['Year'] <= 2017)].copy()
df_all = df_all.drop_duplicates(subset=['Player', 'Year'], keep='first')

# Calculate the mean for all players
yearly_vol_all = df_all.groupby('Year')['3PA'].mean()

# Visualization
plt.figure(figsize=(12, 6))
plt.plot(yearly_vol_all.index, yearly_vol_all.values, marker='o', color='royalblue', linewidth=2.5, label='Avg 3PA (All Players)')

plt.title('NBA Evolution: Average 3-Point Attempts - All Players (1997-2017)', fontsize=15, fontweight='bold')
plt.xlabel('Year', fontsize=12)
plt.ylabel('Average 3PA per Player', fontsize=12)
plt.xlim(1997, 2017)
plt.xticks(range(1997, 2018, 2))
plt.grid(True, linestyle='--', alpha=0.6)
plt.legend(loc='upper left', shadow=True)
plt.show()
plt.savefig('nba_revolution_plot.png', dpi=300)

# 1. Filter for the years 1997-2017 and remove trade duplicates
df_acc = df[(df['Year'] >= 1997) & (df['Year'] <= 2017)].copy()
df_acc = df_acc.drop_duplicates(subset=['Player', 'Year'], keep='first')

# 2. Calculate Shooting Percentage for ALL players
# We use fillna(0) because players with 0 attempts would result in 'NaN'
df_acc['3P_Pct'] = df_acc['3P'] / df_acc['3PA']
df_acc['3P_Pct'] = df_acc['3P_Pct'].fillna(0)

# 3. Calculate the mean accuracy for the whole league
yearly_accuracy = df_acc.groupby('Year')['3P_Pct'].mean()

# 4. Visualization
plt.figure(figsize=(12, 6))
plt.plot(yearly_accuracy.index, yearly_accuracy.values,
         marker='s', color='forestgreen', linewidth=2.5, label='Avg 3P Accuracy (League Wide)')

# 5. Styling in English
plt.title('NBA Evolution: Average 3-Point Accuracy - All Players (1997-2017)', fontsize=15, fontweight='bold')
plt.xlabel('Year', fontsize=12)
plt.ylabel('3-Point Percentage (3P%)', fontsize=12)

# Legend and Axis formatting
plt.legend(loc='upper left', shadow=True)
plt.xlim(1997, 2017)
plt.xticks(range(1997, 2018, 2))

# Important: We adjust the Y-limit to show the lower accuracy of the entire league
plt.ylim(0.20, 0.35)
plt.grid(True, linestyle='--', alpha=0.6)

plt.show()
plt.savefig('nba_revolution_plot.png', dpi=300)

# 1. Prepare Data - 1997-2017, Clean Trades
df_final = df[(df['Year'] >= 1997) & (df['Year'] <= 2017)].copy()
df_final = df_final.drop_duplicates(subset=['Player', 'Year'], keep='first')

# 2. Calculate Pct for ALL players (handling division by zero)
df_final['3P_Pct'] = df_final['3P'] / df_final['3PA']
df_final['3P_Pct'] = df_final['3P_Pct'].fillna(0) # Fill 0 for players with no attempts

# 3. Aggregate - MEAN for ALL players
# This will match your first graph where 2017 is around 140
combined_all = df_final.groupby('Year').agg({
    '3PA': 'mean',
    '3P_Pct': 'mean'
})

# 4. Create Visualization
fig, ax1 = plt.subplots(figsize=(14, 8))

# Primary Axis: Volume (Bars) - Now showing the 140 avg
ax1.bar(combined_all.index, combined_all['3PA'], color='skyblue', alpha=0.4, label='Avg 3PA (All League)')
ax1.set_xlabel('Season (Year)', fontsize=12, fontweight='bold')
ax1.set_ylabel('Average Attempts (League Wide)', color='navy', fontsize=12, fontweight='bold')
ax1.tick_params(axis='y', labelcolor='navy')

# Secondary Axis: Accuracy (Line)
ax2 = ax1.twinx()
ax2.plot(combined_all.index, combined_all['3P_Pct'], color='crimson', marker='o', linewidth=3, label='Avg 3P Accuracy %')
ax2.set_ylabel('Average Accuracy %', color='crimson', fontsize=12, fontweight='bold')
ax2.tick_params(axis='y', labelcolor='crimson')

# Set specific limits to make the graph clear
ax2.set_ylim(0.20, 0.40) # Accuracy for the WHOLE league is lower (around 25-30%)
plt.xlim(1996.5, 2017.5)
plt.xticks(range(1997, 2018, 2))

plt.title('NBA 3-Point Revolution: League-Wide Trends (1997-2017)', fontsize=18, fontweight='bold')
ax1.grid(axis='y', linestyle='--', alpha=0.3)

# Legend
lines1, labels1 = ax1.get_legend_handles_labels()
lines2, labels2 = ax2.get_legend_handles_labels()
ax2.legend(lines1 + lines2, labels1 + labels2, loc='upper left', shadow=True)

plt.show()
plt.savefig('nba_revolution_plot.png', dpi=300)

# 1. Re-defining the clean data for positions
df_pos_acc = df[(df['Year'] >= 1997) & (df['Year'] <= 2017)].copy()
df_pos_acc = df_pos_acc.drop_duplicates(subset=['Player', 'Year'], keep='first')

# 2. Clean positions (
df_pos_acc['Pos_Clean'] = df_pos_acc['Pos'].str.split('-').str[0]

# 3. Calculate 3P% and handle missing values
df_pos_acc['3P_Pct'] = df_pos_acc['3P'] / df_pos_acc['3PA']
df_pos_acc['3P_Pct'] = df_pos_acc['3P_Pct'].fillna(0)

# 4. Filter specifically for 1997, 2007, and 2017 to show the evolution
years_to_show = [1997, 2007, 2017]
df_comparison = df_pos_acc[df_pos_acc['Year'].isin(years_to_show)]

# 5. Create the Pivot Table for the Bar Chart
# Rows: Positions, Columns: Selected Years
pos_bar_data = df_comparison.pivot_table(index='Pos_Clean', columns='Year', values='3P_Pct', aggfunc='mean')

# Reorder to traditional NBA positions
traditional_order = ['PG', 'SG', 'SF', 'PF', 'C']
pos_bar_data = pos_bar_data.reindex(traditional_order)

# 6. Visualization - Grouped Bar Chart
pos_bar_data.plot(kind='bar', figsize=(12, 7), color=['#A9CCE3', '#5499C7', '#154360'], edgecolor='black')

# Styling
plt.title('NBA Evolution: 3P% Accuracy by Position (1997 vs 2007 vs 2017)', fontsize=16, fontweight='bold')
plt.ylabel('Average Shooting Percentage (3P%)', fontsize=12)
plt.xlabel('Position', fontsize=12)
plt.xticks(rotation=0) # Keeps position names horizontal
plt.legend(title='Season', shadow=True)
plt.grid(axis='y', linestyle='--', alpha=0.4)

plt.show()
plt.savefig('nba_revolution_plot.png', dpi=300)

# 1. Filter data for the last 20 years and remove duplicates
df_players = df[(df['Year'] >= 1997) & (df['Year'] <= 2017)].copy()
df_players = df_players.drop_duplicates(subset=['Player', 'Year'], keep='first')

# 2. Group by Player to sum their total 3P and 3PA over the entire period
career_stats = df_players.groupby('Player').agg({
    '3P': 'sum',
    '3PA': 'sum'
})

# 3. Calculate career 3P% for this period
career_stats['3P_Pct'] = career_stats['3P'] / career_stats['3PA']

  # 4. Set a minimum threshold to ensure they are consistent shooters
  # (e.g., at least 500 attempts over 20 years)
min_attempts = 500
top_shooters = career_stats[career_stats['3PA'] >= min_attempts].copy()

  # 5. Sort by percentage and take the top 10
top_10_shooters = top_shooters.sort_values(by='3P_Pct', ascending=False).head(10)

# Display the results
print(f"Top 10 3-Point Shooters (1997-2017) with at least {min_attempts} attempts:")
print(top_10_shooters[['3PA', '3P_Pct']])

# 1. Preparation: Sort the data
top_10_plot = top_10_shooters.sort_values(by='3P_Pct', ascending=True) # Ascending for horizontal bar

# 2. Visualization
plt.figure(figsize=(12, 8))
bars = plt.barh(top_10_plot.index, top_10_plot['3P_Pct'], color='skyblue', edgecolor='navy')

# 3. Styling
plt.title('Top 10 NBA 3-Point Shooters: Career Accuracy (1997-2017)', fontsize=16, fontweight='bold', pad=20)
plt.xlabel('3-Point Percentage (3P%)', fontsize=12)
plt.xlim(0.40, 0.45) # Zoom in to see the small differences between legends
plt.grid(axis='x', linestyle='--', alpha=0.6)

# 4. Adding labels to the bars (The exact percentage)
for bar in bars:
    width = bar.get_width()
    plt.text(width + 0.001, bar.get_y() + bar.get_height()/2,
             f'{width:.2%}', va='center', fontsize=10, fontweight='bold')

plt.tight_layout()
plt.show()
plt.savefig('nba_revolution_plot.png', dpi=300)

from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler
import seaborn as sns
import matplotlib.pyplot as plt

# All the shooters with atleast 500 shots
x = top_shooters[['3PA', '3P_Pct']]

# Scaling The Data
scaler = StandardScaler()
x_scaled = scaler.fit_transform(x)

print("Data is scaled and ready for clustering!")

# Initialize an empty list to store the Within-Cluster Sum of Squares (WCSS)
wcss = []

# Loop through 1 to 10 potential clusters to find the optimal 'k'
for i in range(1, 11):
    # Initialize KMeans with the current number of clusters (i)
    # k-means++ ensures a smarter initialization of centroids
    kmeans = KMeans(n_clusters=i, init='k-means++', random_state=42)

    # Fit the model to our scaled features (3PA and 3P_Pct)
    kmeans.fit(x_scaled)

    # Inertia calculates the sum of squared distances of samples to their closest cluster center
    wcss.append(kmeans.inertia_)

# Visualization of the Elbow Curve
plt.figure(figsize=(10, 6))
plt.plot(range(1, 11), wcss, marker='o', linestyle='--', color='b')

# Adding descriptive titles and labels for the analysis
plt.title('The Elbow Method for Optimal K (NBA 3P Analysis)', fontsize=15)
plt.xlabel('Number of Clusters (k)', fontsize=12)
plt.ylabel('WCSS (Inertia)', fontsize=12)

# Set x-axis ticks to show every cluster number clearly
plt.xticks(range(1, 11))
plt.grid(True)
plt.show()

# 1. Running the final KMeans with k=3 (Using the scaled data from Step 1)
kmeans = KMeans(n_clusters=3, init='k-means++', random_state=42)
top_shooters['Cluster'] = kmeans.fit_predict(x_scaled)

# 2. Mapping cluster numbers to names based on your specific visual results:

cluster_labels = {
    2: 'Elite Superstars',      # High Volume & Solid Accuracy
    1: 'Steady Contributors',    # Lower accuracy or developmental volume
    0: 'High-Accuracy Snipers', # High Accuracy but Lower Volume

}
top_shooters['Archetype'] = top_shooters['Cluster'].map(cluster_labels)

# 3. Visualization: Creating the final clear scatter plot
plt.figure(figsize=(12, 8))
sns.scatterplot(data=top_shooters, x='3PA', y='3P_Pct', hue='Archetype',
                palette={'Elite Superstars': 'green',
                         'High-Accuracy Snipers': 'orange',
                         'Steady Contributors': 'blue'},
                s=100, alpha=0.8, edgecolor='black')

# Adding visual guides and labels
plt.title('NBA Player Archetypes: Volume vs. Accuracy (K-Means Clustering)', fontsize=16, fontweight='bold')
plt.xlabel('Career 3-Point Attempts (Volume)', fontsize=12)
plt.ylabel('3-Point Percentage (Efficiency)', fontsize=12)
plt.legend(title='Player Archetype', loc='upper right')
plt.grid(True, linestyle='--', alpha=0.5)



# List of legends to highlight on the graph
legends_to_label = ['Stephen Curry', 'Ray Allen', 'James Harden', 'Kyle Korver','Kobe Bryant']

# Loop through the dataframe and add text labels for these specific players
for i, row in top_shooters.iterrows():
    if i in legends_to_label:
        plt.text(row['3PA'] + 100, row['3P_Pct'], i,
                 fontsize=10, fontweight='bold', color='black', alpha=0.9)


# 4. Verification: Print the top legends in the 'Elite' category to confirm
print( "Top 15 High-Volume Legends found in 'Elite Superstars'")
# Sorting by 3PA to find the most famous high-volume shooters
elite_players = top_shooters[top_shooters['Archetype'] == 'Elite Superstars']
print(elite_players.sort_values(by='3PA', ascending=False).head(15)[['3PA', '3P_Pct']])

!pip install nba_api

import matplotlib.pyplot as plt
from matplotlib.patches import Circle, Rectangle, Arc
from nba_api.stats.endpoints import shotchartdetail
import pandas as pd
import time


def draw_court(ax=None, color='black', lw=2, outer_lines=False):
    if ax is None:
        ax = plt.gca()

    hoop = Circle((0, 0), radius=7.5, linewidth=lw, color="red", fill=False)
    backboard = Rectangle((-30, -7.5), 60, -1, linewidth=lw, color=color)

    outer_box = Rectangle((-80, -47.5), 160, 190, linewidth=lw, color=color, fill=False)
    inner_box = Rectangle((-60, -47.5), 120, 190, linewidth=lw, color=color, fill=False)

    top_free_throw = Arc((0, 142.5), 120, 120, theta1=0, theta2=180, linewidth=lw, color=color, fill=False)
    bottom_free_throw = Arc((0, 142.5), 120, 120, theta1=180, theta2=0, linewidth=lw, color=color, linestyle='dashed')

    restricted = Arc((0, 0), 80, 80, theta1=0, theta2=180, linewidth=lw, color=color)

    corner_three_a = Rectangle((-220, -47.5), 0, 140, linewidth=lw, color=color)
    corner_three_b = Rectangle((220, -47.5), 0, 140, linewidth=lw, color=color)
    three_arc = Arc((0, 0), 475, 475, theta1=22, theta2=158, linewidth=lw, color=color)

    court_elements = [hoop, backboard, outer_box, inner_box, top_free_throw,
                      bottom_free_throw, restricted, corner_three_a,
                      corner_three_b, three_arc]

    for element in court_elements:
        ax.add_patch(element)
    return ax

def get_season_shot_data(season_year):
    shot_data = shotchartdetail.ShotChartDetail(
        team_id=0, player_id=0, context_measure_simple='FGA',
        season_nullable=season_year, season_type_all_star='Regular Season'
    )
    return shot_data.get_data_frames()[0]

# Downloading Data
shots_2003 = get_season_shot_data('2003-04')
time.sleep(1)
shots_2022 = get_season_shot_data('2022-23')

fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(20, 10))

# הגדרות משותפות ל-Hexbin
grid = (40, 40)
ext = (-250, 250, -50, 420)

# עונת 2003-04
hb1 = ax1.hexbin(shots_2003['LOC_X'], shots_2003['LOC_Y'], gridsize=grid, extent=ext, cmap='inferno', bins='log')
draw_court(ax1)
ax1.set_title('NBA Shot Selection: 2003-04', fontsize=18, fontweight='bold')
ax1.set_axis_off()

# עונת 2022-23
hb2 = ax2.hexbin(shots_2022['LOC_X'], shots_2022['LOC_Y'], gridsize=grid, extent=ext, cmap='inferno', bins='log')
draw_court(ax2)
ax2.set_title('NBA Shot Selection: 2022-23', fontsize=18, fontweight='bold')
ax2.set_axis_off()

cbar_ax = fig.add_axes([1, 0.15, 0.02, 0.7])
cbar = fig.colorbar(hb2, cax=cbar_ax)

cbar.set_label('Frequency of Shots (Brighter = More Shots)', fontsize=12, fontweight='bold')

plt.suptitle('The Visual Impact of the 3-Point Revolution', fontsize=24, y=0.98)
plt.tight_layout()
plt.show()

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt


df = pd.read_excel('/content/NBA-Team-Stats.xlsx')
print(df.shape)
df.head()

# 2. Remove "League Average" rows
# These rows represent the average of all teams and can skew our correlation analysis
df = df[~df['Team'].str.contains('Average|League', na=False)]

# 3. Clean missing values
# We drop rows where crucial columns for our research (3PA, Win%, Season) are empty
critical_columns = ['three_pointers_attempted', 'win_percentage', 'season']
df = df.dropna(subset=critical_columns)

# 4. Convert Season string to a numeric year
# Example: '2023-24' becomes 2023 (integer) for easier calculation and plotting
df['year_numeric'] = df['season'].apply(lambda x: int(str(x).split('-')[0]))

# 5. Filter by Games Played
# We keep only teams that played more than 50 games to avoid outliers from shortened seasons
df = df[df['games_played'] > 50]

# Display the first few rows and confirmation message
print("Data Loading and Cleaning Complete.")
print(f"Total records remaining: {len(df)}")
print(df[['Team', 'season', 'three_pointers_attempted', 'win_percentage']].head())

# CALCULATIONS AND CORRELATIONS

# 1. Defining Eras for the Analysis
# We split the history into 3 periods to see how the impact of 3-pointers evolved
def assign_era(year):
    if year < 2012:
        return "Early 2000s (Mid-Range Era)"
    elif year < 2018:
        return "The Curry Surge (2012-2017)"
    else:
        return "The Modern 3PT Era (2018-2024)"

# Apply the function to create the 'Era' column
df['Era'] = df['year_numeric'].apply(assign_era)

# 2. Calculating the 3-Point Attempt Rate (3PAr)
# This shows what percentage of all shots taken by the team were 3-pointers
# Formula: 3PA / Total Field Goal Attempts
df['three_point_attempt_rate'] = df['three_pointers_attempted'] / df['field_goals_attempted']

# 3. Statistical Correlation Analysis
# We want to see how strongly 3-point volume (3PA) relates to winning (Win%) in each Era
# A correlation of 1.0 means they are perfectly linked.  0.0 means no link at all.
era_correlations = df.groupby('Era').apply(
    lambda x: x['three_pointers_attempted'].corr(x['win_percentage'])
).reset_index()

# Renaming columns for clarity
era_correlations.columns = ['Era', 'Correlation_3PA_to_Wins']

# 4. Displaying the results
print("Correlation Results by Era ")
print("This shows how much throwing more 3s helped in winning:")
print(era_correlations)

print("\n Summary Statistics for the Modern Era")
modern_stats = df[df['Era'] == "The Modern 3PT Era (2018-2024)"]
print(f"Average 3PAr: {modern_stats['three_point_attempt_rate'].mean():.2%}")

# ADVANCED VISUALIZATION
# Set the visual style
sns.set_theme(style="whitegrid")
plt.rcParams['figure.dpi'] = 120
df['3PA_per_game'] = df['three_pointers_attempted'] / df['games_played']

# 1. Create a figure with two subplots
fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(20, 8))

# GRAPH A: The Shift in Volume (3PA vs Win%)
# This will show how the entire league moved to the right over the years
sns.scatterplot(data=df, x="3PA_per_game", y="win_percentage",
                hue="Era", palette="viridis", alpha=0.6, ax=ax1)
ax1.set_title("Evolution of 3PT Volume vs. Win Percentage", fontsize=16, fontweight='bold')
ax1.set_xlabel("3-Point Attempts per Game (3PA)")
ax1.set_ylabel("Win Percentage (W/L%)")
ax1.axhline(0.5, color='black', linestyle='--', alpha=0.3)

# GRAPH B: The Shift in Efficiency (3P% vs Win%)
# This might show a stronger correlation in the modern era
sns.regplot(data=df[df['Era'] == "The Modern 3PT Era (2018-2024)"],
            x="three_point_percentage", y="win_percentage",
            scatter_kws={'color':'teal', 'alpha':0.3}, line_kws={'color':'red'}, ax=ax2)
ax2.set_title("Modern Era: Accuracy (3P%) is Now the Key to Winning", fontsize=16, fontweight='bold')
ax2.set_xlabel("3-Point Percentage (3P%)")
ax2.set_ylabel("Win Percentage (W/L%)")

plt.tight_layout()
plt.show()


plt.figure(figsize=(12, 6))
for era in df['Era'].unique():
    subset = df[df['Era'] == era]
    sns.kdeplot(subset['3PA_per_game'], label=era, fill=True, alpha=0.3)

plt.title("Distribution of 3PT Attempts: How the 'Normal' has Changed", fontsize=15)
plt.xlabel("3-Point Attempts per Game")
plt.ylabel("Density")
plt.legend()
plt.show()

# Finding The Top 5 Winning % Accurate Teams
elite_teams = df[df['win_percentage'] > 0.60].copy()
top_5 = elite_teams.sort_values(by='three_point_percentage', ascending=False).head(5)
top_5['Team_Season'] = top_5['Team'] + "\n(" + top_5['season'] + ")"

# Lollipop Plot Style
plt.figure(figsize=(12, 8))
sns.set_style("white")

colors = ['#E63946', '#457B9D', '#2A9D8F', '#F4A261', '#6D597A']

plt.hlines(y=top_5['Team_Season'], xmin=38, xmax=top_5['three_point_percentage'],
           color='gray', alpha=0.5, linewidth=2)

for i, (idx, row) in enumerate(top_5.iterrows()):
    plt.scatter(row['three_point_percentage'], row['Team_Season'],
                color=colors[i], s=400, edgecolors='black', zorder=3)

    plt.text(row['three_point_percentage'] + 0.4, row['Team_Season'],
             f"{row['three_point_percentage']}% Accuracy\n{row['win_percentage']:.1%} Wins",
             va='center', fontsize=11, fontweight='bold', color=colors[i])

plt.title("The Ultimate Sharp-Shooting Teams", fontsize=22, fontweight='bold', pad=30, loc='left')
plt.xlabel("3-Point Percentage (%)", fontsize=14, labelpad=15)
plt.ylabel("WIN RATE (Win Percentage)", fontsize=14, fontweight='bold')
plt.xlim(38, 43)
plt.gca().invert_yaxis()
plt.grid(axis='x', linestyle='--', alpha=0.3)
sns.despine(left=True, bottom=True)

plt.tight_layout()
plt.show()

# The Future: Extended Linar Regression Forcast To 2034

from sklearn.linear_model import LinearRegression
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

#
# Grouping data by year to find the average league-wide 3PA per game for each season
league_trend = df.groupby('year_numeric')['3PA_per_game'].mean().reset_index()

# 2. BUILDING THE REGRESSION MODEL
# x = Years (Features), y = 3PA per game (Target)
x = league_trend['year_numeric'].values.reshape(-1, 1)
y = league_trend['3PA_per_game'].values

# Initialize and train the Linear Regression model
model = LinearRegression()
model.fit(x, y)

# 3. GENERATING LONG-TERM PREDICTIONS (Up to 2034)
# We create a range starting from the next season (2024) up to 2034
future_years = np.array(range(2024, 2035)).reshape(-1, 1)
future_preds = model.predict(future_years)

# 4. VISUALIZATION OF THE LONG-TERM TREND
plt.figure(figsize=(14, 7))
sns.set_style("whitegrid")

# Plotting historical data points
plt.scatter(x, y, color='#457B9D', label='Historical Data (2000-2023)', s=60, alpha=0.8)

# Plotting the regression trend line (Linear fit)
plt.plot(x, model.predict(X), color='#1D3557', linestyle='--', linewidth=2, label='Linear Trendline')

# Plotting the extended forecast up to 2034
plt.plot(future_years, future_preds, color='#E63946', marker='o', markersize=8, linewidth=2, label='Forecast to 2034')

# Highlighting the 2034 prediction result
plt.text(2034, future_preds[-1] + 1.5, f"2034 Prediction: {future_preds[-1]:.1f} 3PA",
         ha='center', fontsize=12, fontweight='bold', color='#E63946', bbox=dict(facecolor='white', alpha=0.8))

# Finalizing the chart aesthetics
plt.title("NBA Long-Term Forecast: The Evolution of Three-Point Shooting (2000-2034)", fontsize=20, fontweight='bold', pad=25)
plt.xlabel("Year", fontsize=14)
plt.ylabel("Avg 3PA per Game (League Wide)", fontsize=14)
plt.xticks(np.arange(2000, 2035, 2)) # Setting x-axis ticks to show every 2 years
plt.legend(loc='upper left', frameon=True)

plt.tight_layout()
plt.show()

# Print summary
print(f"2034 Prediction : According to the current trend, NBA teams will attempt {future_preds[-1]:.2f} three-pointers per game by 2034.")